import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const meals = [
  {
    name: "Pâtes carbonara",
    category: "PASTA",
    tags: ["rapide", "classique"],
    prepTime: 10, cookTime: 20, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 8,
    ingredients: [
      { name: "spaghetti", quantity: 400, unit: "g" },
      { name: "lardons fumés", quantity: 200, unit: "g" },
      { name: "oeufs", quantity: 4, unit: "" },
      { name: "parmesan râpé", quantity: 80, unit: "g" },
      { name: "poivre noir", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Un grand classique de la cuisine italienne, crémeux et savoureux, prêt en 30 minutes.",
      steps: [
        { stepNumber: 1, description: "Faire cuire les spaghetti al dente dans une grande casserole d'eau bouillante salée.", duration: 10 },
        { stepNumber: 2, description: "Faire revenir les lardons à la poêle sans matière grasse jusqu'à ce qu'ils soient dorés.", duration: 5 },
        { stepNumber: 3, description: "Battre les œufs avec le parmesan et beaucoup de poivre noir.", duration: 2 },
        { stepNumber: 4, description: "Égoutter les pâtes en gardant un peu d'eau de cuisson. Hors du feu, mélanger rapidement avec les lardons puis le mélange œufs-parmesan.", duration: 3 },
        { stepNumber: 5, description: "Ajouter un peu d'eau de cuisson pour obtenir une texture crémeuse. Servir immédiatement.", duration: 2 },
      ],
      tips: ["Ne jamais mettre de crème fraîche dans une vraie carbonara", "Travailler hors du feu pour éviter de faire brouiller les œufs"],
      variations: ["Remplacer les lardons par de la pancetta", "Ajouter des courgettes sautées pour plus de légumes"],
      nutritionEstimate: { calories: 620, proteins: 28, carbs: 72, fats: 24 },
    },
  },
  {
    name: "Buddha bowl tahini",
    category: "SALAD",
    tags: ["végé", "healthy", "coloré"],
    prepTime: 20, cookTime: 25, difficulty: "EASY", budget: "NORMAL",
    servings: 2, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 12,
    ingredients: [
      { name: "riz complet", quantity: 200, unit: "g" },
      { name: "pois chiches", quantity: 400, unit: "g" },
      { name: "avocat", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "tahini", quantity: 3, unit: "cs" },
      { name: "citron", quantity: 1, unit: "" },
    ],
    recipe: {
      intro: "Un bol équilibré, coloré et rassasiant. Parfait pour se faire plaisir sainement.",
      steps: [
        { stepNumber: 1, description: "Cuire le riz complet selon les indications. Rincer et égoutter les pois chiches.", duration: 25 },
        { stepNumber: 2, description: "Éplucher et râper les carottes. Couper le concombre en rondelles, l'avocat en tranches.", duration: 8 },
        { stepNumber: 3, description: "Préparer la sauce : mélanger le tahini avec le jus de citron, une gousse d'ail pressée et 3 cs d'eau.", duration: 3 },
        { stepNumber: 4, description: "Faire revenir les pois chiches à la poêle avec paprika, sel et huile d'olive 5 min.", duration: 5 },
        { stepNumber: 5, description: "Assembler les bols avec le riz, les légumes et les pois chiches. Arroser de sauce tahini.", duration: 3 },
      ],
      tips: ["Préparer le riz et les pois chiches à l'avance pour gagner du temps", "Ajouter des graines de sésame pour le croquant"],
      variations: ["Remplacer le riz par du quinoa", "Utiliser de la patate douce rôtie"],
      nutritionEstimate: { calories: 520, proteins: 18, carbs: 68, fats: 20 },
    },
  },
  {
    name: "Saumon en papillote citron",
    category: "FISH",
    tags: ["healthy", "rapide", "poisson"],
    prepTime: 10, cookTime: 20, difficulty: "EASY", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: true, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 18,
    ingredients: [
      { name: "filets de saumon", quantity: 4, unit: "" },
      { name: "citron", quantity: 2, unit: "" },
      { name: "aneth frais", quantity: 1, unit: "bouquet" },
      { name: "huile d'olive", quantity: 2, unit: "cs" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
      { name: "ail", quantity: 2, unit: "gousses" },
    ],
    recipe: {
      intro: "Une cuisson douce et parfumée qui préserve toute la saveur du saumon.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four à 200°C. Découper des feuilles de papier aluminium.", duration: 5 },
        { stepNumber: 2, description: "Placer chaque filet de saumon sur une feuille d'alu. Assaisonner de sel, poivre, ail haché.", duration: 3 },
        { stepNumber: 3, description: "Ajouter des rondelles de citron, l'aneth et un filet d'huile d'olive. Fermer les papillotes.", duration: 3 },
        { stepNumber: 4, description: "Cuire au four 15 à 20 minutes selon l'épaisseur des filets.", duration: 20 },
      ],
      tips: ["Ne pas trop cuire pour garder le saumon fondant", "Servir avec du riz ou des légumes vapeur"],
      variations: ["Remplacer le citron par de l'orange", "Ajouter des tomates cerises dans la papillote"],
      nutritionEstimate: { calories: 380, proteins: 35, carbs: 2, fats: 25 },
    },
  },
  {
    name: "Soupe de lentilles corail",
    category: "SOUP",
    tags: ["végé", "réconfortant", "économique"],
    prepTime: 10, cookTime: 25, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["AUTUMN", "WINTER"], estimatedCost: 5,
    ingredients: [
      { name: "lentilles corail", quantity: 300, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "carotte", quantity: 2, unit: "" },
      { name: "tomates pelées", quantity: 400, unit: "g" },
      { name: "cumin", quantity: 2, unit: "cc" },
      { name: "curcuma", quantity: 1, unit: "cc" },
      { name: "bouillon de légumes", quantity: 1, unit: "litre" },
    ],
    recipe: {
      intro: "Une soupe dorée, épicée et nourrissante, prête en moins de 40 minutes.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon émincé dans l'huile d'olive avec le cumin et le curcuma.", duration: 5 },
        { stepNumber: 2, description: "Ajouter les carottes en rondelles et les tomates. Cuire 3 minutes.", duration: 3 },
        { stepNumber: 3, description: "Ajouter les lentilles rincées et le bouillon. Porter à ébullition puis mijoter 20 min.", duration: 25 },
        { stepNumber: 4, description: "Mixer en soupe lisse. Rectifier l'assaisonnement.", duration: 3 },
      ],
      tips: ["Se conserve 3 jours au réfrigérateur et se congèle très bien", "Ajouter un filet de crème de coco pour plus d'onctuosité"],
      variations: ["Ajouter du gingembre frais", "Servir avec des croûtons à l'ail"],
      nutritionEstimate: { calories: 280, proteins: 16, carbs: 42, fats: 5 },
    },
  },
  {
    name: "Pizza maison",
    category: "PIZZA_TART",
    tags: ["fun", "enfants", "à personnaliser"],
    prepTime: 30, cookTime: 15, difficulty: "MEDIUM", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 9,
    ingredients: [
      { name: "farine", quantity: 500, unit: "g" },
      { name: "levure boulangère", quantity: 7, unit: "g" },
      { name: "eau tiède", quantity: 300, unit: "ml" },
      { name: "sauce tomate", quantity: 200, unit: "ml" },
      { name: "mozzarella", quantity: 250, unit: "g" },
      { name: "jambon ou légumes", quantity: 200, unit: "g" },
    ],
    recipe: {
      intro: "Rien de tel qu'une pizza faite maison pour ravir toute la famille !",
      steps: [
        { stepNumber: 1, description: "Dissoudre la levure dans l'eau tiède avec une pincée de sucre. Attendre 10 min.", duration: 10 },
        { stepNumber: 2, description: "Mélanger la farine et le sel, créer un puits, verser l'eau. Pétrir 8 minutes.", duration: 15 },
        { stepNumber: 3, description: "Laisser lever la pâte 1h dans un endroit chaud, couverte.", duration: 60 },
        { stepNumber: 4, description: "Étaler la pâte, garnir de sauce tomate et des ingrédients choisis.", duration: 10 },
        { stepNumber: 5, description: "Cuire au four à 230°C pendant 12 à 15 minutes.", duration: 15 },
      ],
      tips: ["Préparer la pâte la veille pour plus de goût", "Cuire sur une pierre à pizza pour une croûte croustillante"],
      variations: ["Pizza blanche crème fraîche-champignons", "Pizza 4 fromages"],
      nutritionEstimate: { calories: 550, proteins: 22, carbs: 75, fats: 18 },
    },
  },
  {
    name: "Curry de pois chiches",
    category: "VEGAN",
    tags: ["végé", "épicé", "indien"],
    prepTime: 10, cookTime: 25, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 7,
    ingredients: [
      { name: "pois chiches", quantity: 800, unit: "g" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "curry", quantity: 2, unit: "cs" },
      { name: "gingembre", quantity: 1, unit: "cc" },
    ],
    recipe: {
      intro: "Un curry onctueux et parfumé, économique et prêt en 30 minutes.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon haché dans l'huile. Ajouter curry et gingembre, cuire 2 min.", duration: 5 },
        { stepNumber: 2, description: "Ajouter les tomates concassées, cuire 5 minutes.", duration: 5 },
        { stepNumber: 3, description: "Ajouter les pois chiches et le lait de coco. Mijoter 20 minutes.", duration: 20 },
        { stepNumber: 4, description: "Servir avec du riz basmati et de la coriandre fraîche.", duration: 2 },
      ],
      tips: ["Écraser quelques pois chiches pour épaissir la sauce", "Ajouter des épinards frais en fin de cuisson"],
      variations: ["Avec des patates douces en dés", "Ajouter du lait de coco avec du beurre de cacahuète"],
      nutritionEstimate: { calories: 380, proteins: 15, carbs: 52, fats: 14 },
    },
  },
  {
    name: "Poulet rôti",
    category: "MEAT",
    tags: ["classique", "dominical", "convivial"],
    prepTime: 15, cookTime: 90, difficulty: "EASY", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 16,
    ingredients: [
      { name: "poulet entier", quantity: 1800, unit: "g" },
      { name: "ail", quantity: 4, unit: "gousses" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "thym et romarin", quantity: 1, unit: "bouquet" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Le grand classique du dimanche, doré et savoureux. Un plat qui fait toujours l'unanimité.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four à 200°C. Frotter le poulet avec le beurre mou, sel et poivre.", duration: 5 },
        { stepNumber: 2, description: "Farcir la cavité avec l'ail, le citron coupé et les herbes.", duration: 5 },
        { stepNumber: 3, description: "Placer dans un plat et enfourner 1h30, en arrosant toutes les 30 minutes.", duration: 90 },
        { stepNumber: 4, description: "Laisser reposer 10 minutes avant de découper.", duration: 10 },
      ],
      tips: ["La farce au citron parfume délicatement la chair", "Vérifier la cuisson avec un thermomètre : 75°C à cœur"],
      variations: ["Poulet rôti au paprika fumé", "Avec des pommes de terre rôties dans le plat"],
      nutritionEstimate: { calories: 480, proteins: 42, carbs: 2, fats: 32 },
    },
  },
  {
    name: "Quiche lorraine",
    category: "PIZZA_TART",
    tags: ["classique", "réconfortant"],
    prepTime: 20, cookTime: 35, difficulty: "EASY", budget: "CHEAP",
    servings: 6, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 8,
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "" },
      { name: "lardons fumés", quantity: 200, unit: "g" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "crème fraîche épaisse", quantity: 200, unit: "ml" },
      { name: "lait", quantity: 100, unit: "ml" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "La quiche lorraine traditionnelle, croustillante et crémeuse, une valeur sûre.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four à 180°C. Foncer un moule avec la pâte brisée.", duration: 5 },
        { stepNumber: 2, description: "Faire revenir les lardons sans matière grasse. Égoutter.", duration: 5 },
        { stepNumber: 3, description: "Battre les œufs avec la crème et le lait. Saler, poivrer.", duration: 3 },
        { stepNumber: 4, description: "Répartir les lardons sur la pâte, verser l'appareil et parsemer de gruyère.", duration: 5 },
        { stepNumber: 5, description: "Cuire 35 minutes jusqu'à ce que la quiche soit dorée et prise.", duration: 35 },
      ],
      tips: ["Pré-cuire la pâte à blanc 10 min pour éviter qu'elle soit détrempée"],
      variations: ["Quiche poireaux-jambon", "Version sans pâte pour moins de calories"],
      nutritionEstimate: { calories: 420, proteins: 16, carbs: 24, fats: 30 },
    },
  },
  {
    name: "Risotto aux champignons",
    category: "RICE_GRAINS",
    tags: ["réconfortant", "végé", "crémeux"],
    prepTime: 10, cookTime: 30, difficulty: "MEDIUM", budget: "NORMAL",
    servings: 4, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["AUTUMN", "WINTER"], estimatedCost: 11,
    ingredients: [
      { name: "riz arborio", quantity: 320, unit: "g" },
      { name: "champignons de Paris", quantity: 400, unit: "g" },
      { name: "bouillon de légumes chaud", quantity: 1.2, unit: "litre" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "vin blanc sec", quantity: 100, unit: "ml" },
      { name: "parmesan", quantity: 60, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
    ],
    recipe: {
      intro: "Un risotto onctueux aux champignons, à savourer chaud dès la sortie de la casserole.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon haché dans le beurre. Ajouter les champignons émincés, cuire 5 min.", duration: 8 },
        { stepNumber: 2, description: "Ajouter le riz, nacrer 2 minutes en remuant.", duration: 3 },
        { stepNumber: 3, description: "Déglacer au vin blanc et laisser absorber.", duration: 3 },
        { stepNumber: 4, description: "Ajouter le bouillon chaud louche par louche en remuant constamment.", duration: 20 },
        { stepNumber: 5, description: "Hors du feu, ajouter parmesan et beurre. Remuer vigoureusement (mantecatura).", duration: 2 },
      ],
      tips: ["Le bouillon doit toujours être chaud", "Ne jamais arrêter de remuer pour libérer l'amidon"],
      variations: ["Risotto aux asperges au printemps", "Risotto truffe et parmesan pour les grandes occasions"],
      nutritionEstimate: { calories: 480, proteins: 14, carbs: 68, fats: 16 },
    },
  },
  {
    name: "Tacos maison",
    category: "MEAT",
    tags: ["fun", "enfants", "convivial"],
    prepTime: 20, cookTime: 15, difficulty: "EASY", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 14,
    ingredients: [
      { name: "tortillas de blé", quantity: 8, unit: "" },
      { name: "viande hachée de boeuf", quantity: 500, unit: "g" },
      { name: "épices à tacos", quantity: 2, unit: "cs" },
      { name: "tomates", quantity: 3, unit: "" },
      { name: "laitue iceberg", quantity: 1, unit: "petite" },
      { name: "crème fraîche", quantity: 150, unit: "ml" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
    ],
    recipe: {
      intro: "Des tacos maison colorés et savoureux, prêts en 35 minutes pour toute la famille.",
      steps: [
        { stepNumber: 1, description: "Faire revenir la viande hachée avec les épices jusqu'à brunissement.", duration: 10 },
        { stepNumber: 2, description: "Préparer les garnitures : couper tomates, ciseler la laitue.", duration: 8 },
        { stepNumber: 3, description: "Réchauffer les tortillas 30 secondes par côté à la poêle sèche.", duration: 3 },
        { stepNumber: 4, description: "Garnir chaque tortilla et servir à table avec les garnitures séparées.", duration: 5 },
      ],
      tips: ["Laisser chacun composer son taco pour plus de fun"],
      variations: ["Tacos au poulet grillé", "Version végétarienne avec haricots noirs"],
      nutritionEstimate: { calories: 560, proteins: 32, carbs: 48, fats: 24 },
    },
  },
  {
    name: "Ratatouille provençale",
    category: "VEGETARIAN",
    tags: ["végé", "été", "provençal"],
    prepTime: 25, cookTime: 45, difficulty: "MEDIUM", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["SUMMER", "AUTUMN"], estimatedCost: 8,
    ingredients: [
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "aubergines", quantity: 1, unit: "" },
      { name: "poivrons", quantity: 2, unit: "" },
      { name: "tomates", quantity: 4, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "ail", quantity: 3, unit: "gousses" },
      { name: "herbes de Provence", quantity: 2, unit: "cs" },
    ],
    recipe: {
      intro: "La ratatouille, emblème de la cuisine provençale estivale, fondante et parfumée.",
      steps: [
        { stepNumber: 1, description: "Couper tous les légumes en dés de taille similaire.", duration: 15 },
        { stepNumber: 2, description: "Faire revenir l'oignon et l'ail dans l'huile d'olive.", duration: 5 },
        { stepNumber: 3, description: "Ajouter les légumes un par un en commençant par les poivrons, puis aubergines, courgettes et tomates.", duration: 10 },
        { stepNumber: 4, description: "Assaisonner avec les herbes. Mijoter à feu doux 40 minutes en remuant de temps en temps.", duration: 40 },
      ],
      tips: ["Meilleure le lendemain après une nuit au réfrigérateur", "Cuire les légumes séparément pour plus de saveur"],
      variations: ["Ratatouille en gratin", "Servir froide en entrée avec du pain grillé"],
      nutritionEstimate: { calories: 180, proteins: 4, carbs: 22, fats: 9 },
    },
  },
  {
    name: "Steak-frites",
    category: "MEAT",
    tags: ["classique", "rapide", "enfants"],
    prepTime: 10, cookTime: 25, difficulty: "EASY", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 20,
    ingredients: [
      { name: "steaks de boeuf", quantity: 4, unit: "" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "huile de friture", quantity: 1, unit: "litre" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
      { name: "beurre", quantity: 20, unit: "g" },
    ],
    recipe: {
      intro: "Le classique absolu de la brasserie française, simple et toujours apprécié.",
      steps: [
        { stepNumber: 1, description: "Éplucher et couper les pommes de terre en frites. Rincer et sécher.", duration: 10 },
        { stepNumber: 2, description: "Première friture à 160°C pendant 5 minutes. Égoutter.", duration: 8 },
        { stepNumber: 3, description: "Deuxième friture à 180°C pendant 3 minutes pour dorer. Saler immédiatement.", duration: 5 },
        { stepNumber: 4, description: "Cuire les steaks dans une poêle très chaude avec le beurre selon cuisson souhaitée.", duration: 6 },
      ],
      tips: ["La double cuisson est le secret des frites croustillantes", "Sortir les steaks du réfrigérateur 30 min avant cuisson"],
      variations: ["Frites au four pour une version plus légère", "Sauce béarnaise maison"],
      nutritionEstimate: { calories: 680, proteins: 38, carbs: 52, fats: 32 },
    },
  },
  {
    name: "Pad thaï crevettes",
    category: "STIR_FRY",
    tags: ["asiatique", "rapide", "savoureux"],
    prepTime: 15, cookTime: 15, difficulty: "MEDIUM", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: true, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 16,
    ingredients: [
      { name: "nouilles de riz", quantity: 300, unit: "g" },
      { name: "crevettes décortiquées", quantity: 400, unit: "g" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "sauce poisson", quantity: 3, unit: "cs" },
      { name: "pâte de tamarin", quantity: 2, unit: "cs" },
      { name: "cacahuètes", quantity: 50, unit: "g" },
      { name: "germes de soja", quantity: 100, unit: "g" },
    ],
    recipe: {
      intro: "Le street food thaïlandais par excellence, équilibré entre sucré, salé et acidulé.",
      steps: [
        { stepNumber: 1, description: "Tremper les nouilles de riz dans l'eau froide 30 min. Égoutter.", duration: 30 },
        { stepNumber: 2, description: "Faire sauter les crevettes dans un wok très chaud. Réserver.", duration: 3 },
        { stepNumber: 3, description: "Brouiller les œufs dans le wok. Ajouter les nouilles et la sauce (tamarin + poisson + sucre).", duration: 5 },
        { stepNumber: 4, description: "Ajouter les crevettes, germes de soja. Mélanger. Garnir de cacahuètes concassées.", duration: 3 },
      ],
      tips: ["Wok très chaud pour le Maillard", "Préparer tous les ingrédients avant de commencer"],
      variations: ["Version végétarienne avec tofu", "Ajouter du piment frais pour plus de piquant"],
      nutritionEstimate: { calories: 520, proteins: 28, carbs: 62, fats: 16 },
    },
  },
  {
    name: "Gratin dauphinois",
    category: "VEGETARIAN",
    tags: ["réconfortant", "hivernal", "fondant"],
    prepTime: 20, cookTime: 60, difficulty: "EASY", budget: "CHEAP",
    servings: 6, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["AUTUMN", "WINTER"], estimatedCost: 7,
    ingredients: [
      { name: "pommes de terre", quantity: 1.2, unit: "kg" },
      { name: "crème liquide entière", quantity: 400, unit: "ml" },
      { name: "lait entier", quantity: 200, unit: "ml" },
      { name: "ail", quantity: 2, unit: "gousses" },
      { name: "noix de muscade", quantity: 1, unit: "pincée" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "Le gratin dauphinois authentique, fondant et doré, sans fromage dans la tradition.",
      steps: [
        { stepNumber: 1, description: "Éplucher et trancher finement les pommes de terre à la mandoline.", duration: 15 },
        { stepNumber: 2, description: "Porter à ébullition la crème et le lait avec l'ail et la muscade. Cuire les tranches 5 min.", duration: 8 },
        { stepNumber: 3, description: "Disposer en couches dans un plat à gratin beurré. Verser la crème.", duration: 5 },
        { stepNumber: 4, description: "Saupoudrer de gruyère et cuire 1h à 160°C.", duration: 60 },
      ],
      tips: ["Ne pas rincer les pommes de terre pour garder l'amidon qui lie le gratin"],
      variations: ["Gratin savoyard avec reblochon", "Ajouter des lardons entre les couches"],
      nutritionEstimate: { calories: 380, proteins: 8, carbs: 42, fats: 20 },
    },
  },
  {
    name: "Falafels houmous",
    category: "VEGAN",
    tags: ["végé", "oriental", "healthy"],
    prepTime: 20, cookTime: 20, difficulty: "MEDIUM", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 8,
    ingredients: [
      { name: "pois chiches secs trempés", quantity: 300, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "ail", quantity: 3, unit: "gousses" },
      { name: "coriandre fraîche", quantity: 1, unit: "bouquet" },
      { name: "cumin", quantity: 2, unit: "cc" },
      { name: "farine", quantity: 3, unit: "cs" },
      { name: "houmous", quantity: 200, unit: "g" },
    ],
    recipe: {
      intro: "Des falafels croustillants à l'extérieur et moelleux à l'intérieur, servis avec houmous.",
      steps: [
        { stepNumber: 1, description: "Mixer les pois chiches crus avec oignon, ail, coriandre, cumin. Ne pas trop mixer.", duration: 5 },
        { stepNumber: 2, description: "Ajouter la farine, sel. Laisser reposer 30 min au réfrigérateur.", duration: 30 },
        { stepNumber: 3, description: "Former des boules et frire dans l'huile à 170°C pendant 4 minutes.", duration: 8 },
        { stepNumber: 4, description: "Égoutter sur papier absorbant. Servir avec le houmous et une salade.", duration: 2 },
      ],
      tips: ["Utiliser des pois chiches crus trempés et non cuits", "Se congèlent très bien après friture"],
      variations: ["Au four pour une version moins calorique", "Dans une pita avec tomates et concombre"],
      nutritionEstimate: { calories: 380, proteins: 14, carbs: 46, fats: 16 },
    },
  },
  {
    name: "Chili con carne",
    category: "STEW",
    tags: ["épicé", "réconfortant", "amérique"],
    prepTime: 15, cookTime: 60, difficulty: "EASY", budget: "CHEAP",
    servings: 6, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["AUTUMN", "WINTER"], estimatedCost: 12,
    ingredients: [
      { name: "viande hachée de boeuf", quantity: 600, unit: "g" },
      { name: "haricots rouges", quantity: 400, unit: "g" },
      { name: "tomates concassées", quantity: 800, unit: "g" },
      { name: "oignon", quantity: 2, unit: "" },
      { name: "poivron rouge", quantity: 1, unit: "" },
      { name: "cumin et paprika", quantity: 2, unit: "cs" },
      { name: "piment de Cayenne", quantity: 0.5, unit: "cc" },
    ],
    recipe: {
      intro: "Un chili con carne généreux qui se déguste encore meilleur le lendemain.",
      steps: [
        { stepNumber: 1, description: "Faire revenir oignons et poivrons dans l'huile.", duration: 5 },
        { stepNumber: 2, description: "Ajouter la viande hachée et faire brunir.", duration: 8 },
        { stepNumber: 3, description: "Incorporer épices, tomates et haricots. Porter à ébullition.", duration: 5 },
        { stepNumber: 4, description: "Mijoter à feu doux 45 minutes en remuant régulièrement.", duration: 45 },
      ],
      tips: ["Se bonifie en étant réchauffé le lendemain", "Servir avec du riz, de la crème fraîche et du fromage"],
      variations: ["Chili végétarien avec haricots noirs et maïs", "Version plus douce sans piment"],
      nutritionEstimate: { calories: 440, proteins: 34, carbs: 38, fats: 16 },
    },
  },
  {
    name: "Lasagnes bolognaise",
    category: "PASTA",
    tags: ["classique", "familial", "réconfortant"],
    prepTime: 30, cookTime: 60, difficulty: "MEDIUM", budget: "NORMAL",
    servings: 6, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 15,
    ingredients: [
      { name: "plaques de lasagne", quantity: 12, unit: "" },
      { name: "viande hachée boeuf-veau", quantity: 600, unit: "g" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "lait", quantity: 600, unit: "ml" },
      { name: "farine", quantity: 50, unit: "g" },
      { name: "beurre", quantity: 50, unit: "g" },
      { name: "gruyère râpé", quantity: 150, unit: "g" },
    ],
    recipe: {
      intro: "Des lasagnes bolognaises généreuses, le plat réconfortant par excellence.",
      steps: [
        { stepNumber: 1, description: "Préparer la bolognaise : faire revenir la viande, ajouter tomates et herbes, mijoter 30 min.", duration: 35 },
        { stepNumber: 2, description: "Préparer la béchamel : faire fondre le beurre, ajouter la farine, puis le lait progressivement.", duration: 10 },
        { stepNumber: 3, description: "Monter les lasagnes en alternant bolognaise, plaques et béchamel.", duration: 10 },
        { stepNumber: 4, description: "Terminer par la béchamel et le gruyère. Cuire 40 min à 180°C.", duration: 40 },
      ],
      tips: ["Couvrir les 20 premières minutes avec du papier alu pour éviter de sécher"],
      variations: ["Lasagnes végétarienne épinards-ricotta", "Lasagnes saumon-poireaux"],
      nutritionEstimate: { calories: 580, proteins: 32, carbs: 52, fats: 26 },
    },
  },
  {
    name: "Poké bowl thon",
    category: "SALAD",
    tags: ["healthy", "hawaïen", "frais"],
    prepTime: 20, cookTime: 20, difficulty: "EASY", budget: "NORMAL",
    servings: 2, isVegetarian: false, isVegan: false, isFish: true, canPrepAhead: false,
    season: ["SPRING", "SUMMER"], estimatedCost: 14,
    ingredients: [
      { name: "thon frais ou en boîte", quantity: 300, unit: "g" },
      { name: "riz à sushi", quantity: 200, unit: "g" },
      { name: "avocat", quantity: 1, unit: "" },
      { name: "concombre", quantity: 0.5, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "cs" },
      { name: "sésame", quantity: 1, unit: "cs" },
      { name: "gingembre mariné", quantity: 2, unit: "cs" },
    ],
    recipe: {
      intro: "Un bowl hawaïen frais et coloré, savoureux et rassasiant.",
      steps: [
        { stepNumber: 1, description: "Cuire le riz à sushi, assaisonner avec vinaigre de riz, sucre, sel.", duration: 25 },
        { stepNumber: 2, description: "Mariner le thon coupé en dés dans la sauce soja + sésame 10 min.", duration: 10 },
        { stepNumber: 3, description: "Préparer les garnitures : avocat en tranches, concombre en rondelles.", duration: 5 },
        { stepNumber: 4, description: "Assembler les bols avec le riz, le thon mariné et les légumes.", duration: 3 },
      ],
      tips: ["Avec du thon frais, s'assurer qu'il est de qualité sashimi"],
      variations: ["Poké bowl saumon-mangue", "Version végétarienne avec tofu lacté"],
      nutritionEstimate: { calories: 480, proteins: 32, carbs: 52, fats: 16 },
    },
  },
  {
    name: "Gnocchis gorgonzola",
    category: "PASTA",
    tags: ["réconfortant", "crémeux", "rapide"],
    prepTime: 5, cookTime: 15, difficulty: "EASY", budget: "NORMAL",
    servings: 4, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 10,
    ingredients: [
      { name: "gnocchis frais", quantity: 500, unit: "g" },
      { name: "gorgonzola", quantity: 150, unit: "g" },
      { name: "crème fraîche", quantity: 150, unit: "ml" },
      { name: "noix", quantity: 50, unit: "g" },
      { name: "roquette", quantity: 50, unit: "g" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Des gnocchis gourmands au gorgonzola fondant, prêts en 20 minutes.",
      steps: [
        { stepNumber: 1, description: "Cuire les gnocchis dans l'eau bouillante salée jusqu'à ce qu'ils remontent.", duration: 3 },
        { stepNumber: 2, description: "Faire fondre le gorgonzola dans la crème fraîche à feu doux.", duration: 5 },
        { stepNumber: 3, description: "Égoutter les gnocchis et les enrober de sauce.", duration: 2 },
        { stepNumber: 4, description: "Servir avec les noix concassées et la roquette fraîche.", duration: 2 },
      ],
      tips: ["Ne pas trop cuire les gnocchis pour garder leur texture"],
      variations: ["Avec des épinards et pignons", "Version plus légère avec ricotta à la place du gorgonzola"],
      nutritionEstimate: { calories: 520, proteins: 16, carbs: 58, fats: 26 },
    },
  },
  {
    name: "Poulet tikka masala",
    category: "STEW",
    tags: ["indien", "épicé", "crémeux"],
    prepTime: 20, cookTime: 30, difficulty: "MEDIUM", budget: "NORMAL",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 14,
    ingredients: [
      { name: "filets de poulet", quantity: 700, unit: "g" },
      { name: "yaourt nature", quantity: 150, unit: "g" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "lait de coco", quantity: 200, unit: "ml" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "tikka masala en poudre", quantity: 3, unit: "cs" },
      { name: "gingembre frais", quantity: 2, unit: "cm" },
    ],
    recipe: {
      intro: "Un curry crémeux et parfumé, l'un des plats indiens les plus populaires au monde.",
      steps: [
        { stepNumber: 1, description: "Mariner le poulet en dés dans le yaourt + tikka masala 1h (ou toute la nuit).", duration: 60 },
        { stepNumber: 2, description: "Faire revenir oignon et gingembre. Ajouter le poulet mariné, cuire 10 min.", duration: 12 },
        { stepNumber: 3, description: "Ajouter tomates et lait de coco. Mijoter 20 min.", duration: 20 },
        { stepNumber: 4, description: "Servir avec du riz basmati et de la coriandre fraîche.", duration: 3 },
      ],
      tips: ["Mariner le poulet la veille pour plus de goût"],
      variations: ["Version végétarienne avec paneer ou pois chiches"],
      nutritionEstimate: { calories: 420, proteins: 38, carbs: 18, fats: 22 },
    },
  },
  {
    name: "Tabbouleh libanais",
    category: "SALAD",
    tags: ["végé", "frais", "oriental"],
    prepTime: 20, cookTime: 0, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["SPRING", "SUMMER"], estimatedCost: 6,
    ingredients: [
      { name: "boulghour fin", quantity: 100, unit: "g" },
      { name: "persil plat", quantity: 2, unit: "bouquets" },
      { name: "menthe fraîche", quantity: 0.5, unit: "bouquet" },
      { name: "tomates", quantity: 3, unit: "" },
      { name: "citron", quantity: 2, unit: "" },
      { name: "oignon rouge", quantity: 0.5, unit: "" },
      { name: "huile d'olive", quantity: 4, unit: "cs" },
    ],
    recipe: {
      intro: "Un tabbouleh authentique où les herbes dominent — rafraîchissant et plein de saveurs.",
      steps: [
        { stepNumber: 1, description: "Réhydrater le boulghour dans de l'eau froide 30 min. Égoutter et presser.", duration: 30 },
        { stepNumber: 2, description: "Ciseler finement le persil et la menthe.", duration: 10 },
        { stepNumber: 3, description: "Couper les tomates en petits dés, l'oignon rouge très fin.", duration: 5 },
        { stepNumber: 4, description: "Mélanger tous les ingrédients. Assaisonner avec citron, huile, sel. Réfrigérer 1h.", duration: 5 },
      ],
      tips: ["Le vrai tabbouleh libanais a beaucoup plus d'herbes que de céréales"],
      variations: ["Avec de la feta émiettée", "Remplacer le boulghour par du quinoa"],
      nutritionEstimate: { calories: 180, proteins: 4, carbs: 22, fats: 9 },
    },
  },
  {
    name: "Omelette courgettes chèvre",
    category: "VEGETARIAN",
    tags: ["rapide", "végé", "léger"],
    prepTime: 10, cookTime: 10, difficulty: "EASY", budget: "CHEAP",
    servings: 2, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["SPRING", "SUMMER"], estimatedCost: 6,
    ingredients: [
      { name: "oeufs", quantity: 6, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "chèvre frais", quantity: 100, unit: "g" },
      { name: "basilic frais", quantity: 5, unit: "feuilles" },
      { name: "beurre", quantity: 15, unit: "g" },
    ],
    recipe: {
      intro: "Une omelette légère et savoureuse, parfaite pour un dîner express.",
      steps: [
        { stepNumber: 1, description: "Râper la courgette. Faire revenir dans le beurre 3 minutes.", duration: 5 },
        { stepNumber: 2, description: "Battre les œufs avec sel et poivre.", duration: 2 },
        { stepNumber: 3, description: "Verser les œufs sur les courgettes. Cuire à feu moyen en soulevant les bords.", duration: 5 },
        { stepNumber: 4, description: "Déposer le chèvre et le basilic. Plier et servir.", duration: 2 },
      ],
      tips: ["Ne pas trop cuire pour garder l'omelette baveuse"],
      variations: ["Avec champignons sautés", "Ajouter des tomates séchées"],
      nutritionEstimate: { calories: 320, proteins: 22, carbs: 4, fats: 24 },
    },
  },
  {
    name: "Soupe potiron gingembre",
    category: "SOUP",
    tags: ["hivernal", "végé", "doux"],
    prepTime: 15, cookTime: 30, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: true,
    season: ["AUTUMN", "WINTER"], estimatedCost: 6,
    ingredients: [
      { name: "potiron", quantity: 800, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gingembre frais", quantity: 3, unit: "cm" },
      { name: "lait de coco", quantity: 200, unit: "ml" },
      { name: "bouillon de légumes", quantity: 600, unit: "ml" },
    ],
    recipe: {
      intro: "Une soupe veloutée et réconfortante au parfum chaud de gingembre.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon et le gingembre râpé dans l'huile de coco.", duration: 5 },
        { stepNumber: 2, description: "Ajouter le potiron coupé en dés et le bouillon. Cuire 25 min.", duration: 25 },
        { stepNumber: 3, description: "Mixer avec le lait de coco. Rectifier l'assaisonnement.", duration: 3 },
      ],
      tips: ["Servir avec des graines de courge grillées et un filet d'huile de piment"],
      variations: ["Avec de la courge butternut", "Ajouter une pomme pour la douceur"],
      nutritionEstimate: { calories: 180, proteins: 3, carbs: 22, fats: 9 },
    },
  },
  {
    name: "Frittata épinards feta",
    category: "VEGETARIAN",
    tags: ["végé", "protéiné", "méditerranéen"],
    prepTime: 10, cookTime: 20, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["ALL_YEAR"], estimatedCost: 7,
    ingredients: [
      { name: "oeufs", quantity: 8, unit: "" },
      { name: "épinards frais", quantity: 150, unit: "g" },
      { name: "feta", quantity: 120, unit: "g" },
      { name: "oignon rouge", quantity: 0.5, unit: "" },
      { name: "ail", quantity: 1, unit: "gousse" },
    ],
    recipe: {
      intro: "Une frittata généreuse aux épinards et feta, parfaite chaude ou froide.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon et l'ail dans une poêle allant au four.", duration: 3 },
        { stepNumber: 2, description: "Ajouter les épinards et laisser tomber.", duration: 2 },
        { stepNumber: 3, description: "Verser les œufs battus et la feta émiettée.", duration: 2 },
        { stepNumber: 4, description: "Cuire à feu doux 5 min puis passer sous le grill 5 min.", duration: 10 },
      ],
      tips: ["Se mange froide le lendemain en sandwich"],
      variations: ["Frittata poivrons-olives", "Avec des pommes de terre cuites"],
      nutritionEstimate: { calories: 280, proteins: 20, carbs: 4, fats: 20 },
    },
  },
  {
    name: "Wok de légumes soja",
    category: "STIR_FRY",
    tags: ["vegan", "asiatique", "rapide"],
    prepTime: 15, cookTime: 10, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: true, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 8,
    ingredients: [
      { name: "brocoli", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "poivron rouge", quantity: 1, unit: "" },
      { name: "champignons shitake", quantity: 150, unit: "g" },
      { name: "sauce soja", quantity: 4, unit: "cs" },
      { name: "huile de sésame", quantity: 2, unit: "cc" },
      { name: "nouilles soba", quantity: 200, unit: "g" },
    ],
    recipe: {
      intro: "Un wok coloré et plein de saveurs, prêt en 25 minutes.",
      steps: [
        { stepNumber: 1, description: "Cuire les nouilles soba. Réserver.", duration: 8 },
        { stepNumber: 2, description: "Couper tous les légumes en fines lamelles ou petits bouquets.", duration: 8 },
        { stepNumber: 3, description: "Faire chauffer le wok à feu vif. Ajouter les légumes les uns après les autres par ordre de dureté.", duration: 8 },
        { stepNumber: 4, description: "Ajouter les nouilles, la sauce soja et l'huile de sésame. Mélanger 1 min.", duration: 2 },
      ],
      tips: ["Feu vif et légumes en petits morceaux pour un wok réussi"],
      variations: ["Ajouter du tofu croustillant", "Sauce teriyaki à la place de la sauce soja"],
      nutritionEstimate: { calories: 320, proteins: 12, carbs: 52, fats: 8 },
    },
  },
  {
    name: "Blanquette de veau",
    category: "STEW",
    tags: ["classique", "français", "dimanche"],
    prepTime: 20, cookTime: 90, difficulty: "MEDIUM", budget: "SPLURGE",
    servings: 6, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["AUTUMN", "WINTER"], estimatedCost: 22,
    ingredients: [
      { name: "épaule de veau", quantity: 1.2, unit: "kg" },
      { name: "carottes", quantity: 3, unit: "" },
      { name: "champignons de Paris", quantity: 250, unit: "g" },
      { name: "crème fraîche", quantity: 200, unit: "ml" },
      { name: "oeufs (jaunes)", quantity: 2, unit: "" },
      { name: "bouquet garni", quantity: 1, unit: "" },
    ],
    recipe: {
      intro: "La blanquette de veau, grand classique de la cuisine française bourgeoise.",
      steps: [
        { stepNumber: 1, description: "Blanchir le veau : couvrir d'eau froide, porter à ébullition, rincer.", duration: 10 },
        { stepNumber: 2, description: "Remettre dans une cocotte avec bouillon, carottes et bouquet garni. Cuire 1h.", duration: 65 },
        { stepNumber: 3, description: "Préparer un roux blanc avec beurre et farine. Délayer avec le bouillon de cuisson.", duration: 8 },
        { stepNumber: 4, description: "Ajouter la crème et les jaunes d'œufs à la sauce. Ne plus faire bouillir.", duration: 5 },
        { stepNumber: 5, description: "Ajouter les champignons sautés et la viande. Servir avec du riz.", duration: 5 },
      ],
      tips: ["Ne jamais faire bouillir la sauce après ajout des jaunes d'oeufs"],
      variations: ["Blanquette au cidre", "Version légère avec yaourt à la place de la crème"],
      nutritionEstimate: { calories: 480, proteins: 42, carbs: 14, fats: 28 },
    },
  },
  {
    name: "Crêpes salées complètes",
    category: "PIZZA_TART",
    tags: ["breton", "rapide", "convivial"],
    prepTime: 10, cookTime: 20, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 8,
    ingredients: [
      { name: "farine de blé noir", quantity: 250, unit: "g" },
      { name: "oeufs", quantity: 4, unit: "" },
      { name: "lait", quantity: 500, unit: "ml" },
      { name: "jambon blanc", quantity: 4, unit: "tranches" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
    ],
    recipe: {
      intro: "Des galettes bretonnes croustillantes garnies à votre guise — rapide et festif.",
      steps: [
        { stepNumber: 1, description: "Préparer la pâte : mélanger farine, œufs, lait et sel. Laisser reposer 30 min.", duration: 30 },
        { stepNumber: 2, description: "Cuire chaque galette dans une crêpière beurrée.", duration: 3 },
        { stepNumber: 3, description: "Garnir de jambon, fromage et œuf. Plier en carré et servir.", duration: 2 },
      ],
      tips: ["La pâte de sarrasin peut se préparer la veille"],
      variations: ["Galette chèvre-miel-noix", "Garnissage salmon-crème-aneth"],
      nutritionEstimate: { calories: 420, proteins: 22, carbs: 42, fats: 18 },
    },
  },
  {
    name: "Clafoutis légumes",
    category: "VEGETARIAN",
    tags: ["végé", "rapide", "four"],
    prepTime: 15, cookTime: 35, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: true, isVegan: false, isFish: false, canPrepAhead: true,
    season: ["SPRING", "SUMMER"], estimatedCost: 7,
    ingredients: [
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "tomates cerises", quantity: 200, unit: "g" },
      { name: "oeufs", quantity: 4, unit: "" },
      { name: "lait", quantity: 200, unit: "ml" },
      { name: "farine", quantity: 80, unit: "g" },
      { name: "fromage râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "Un clafoutis salé moelleux et doré, parfait pour vider le frigo.",
      steps: [
        { stepNumber: 1, description: "Couper les légumes. Faire revenir les courgettes à la poêle 5 min.", duration: 8 },
        { stepNumber: 2, description: "Battre les œufs avec le lait et la farine. Assaisonner.", duration: 3 },
        { stepNumber: 3, description: "Disposer les légumes dans un plat huilé. Verser l'appareil et le fromage.", duration: 5 },
        { stepNumber: 4, description: "Cuire 35 min à 180°C.", duration: 35 },
      ],
      tips: ["Peut se servir froid coupé en carrés en entrée"],
      variations: ["Avec des poivrons grillés", "Clafoutis épinards-chèvre"],
      nutritionEstimate: { calories: 280, proteins: 16, carbs: 22, fats: 14 },
    },
  },
  {
    name: "Tarte flambée alsacienne",
    category: "PIZZA_TART",
    tags: ["alsacien", "convivial", "rapide"],
    prepTime: 15, cookTime: 12, difficulty: "EASY", budget: "CHEAP",
    servings: 4, isVegetarian: false, isVegan: false, isFish: false, canPrepAhead: false,
    season: ["ALL_YEAR"], estimatedCost: 9,
    ingredients: [
      { name: "pâte fine à tarte", quantity: 1, unit: "" },
      { name: "crème fraîche épaisse", quantity: 200, unit: "g" },
      { name: "fromage blanc", quantity: 100, unit: "g" },
      { name: "lardons fumés", quantity: 150, unit: "g" },
      { name: "oignon", quantity: 2, unit: "" },
      { name: "noix de muscade", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "La flammekueche authentique, croustillante et généreuse.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four à 250°C. Étaler la pâte très finement.", duration: 5 },
        { stepNumber: 2, description: "Mélanger crème fraîche et fromage blanc. Assaisonner.", duration: 2 },
        { stepNumber: 3, description: "Étaler sur la pâte. Garnir de lardons et oignons émincés fins.", duration: 5 },
        { stepNumber: 4, description: "Cuire 10 à 12 min jusqu'à ce que les bords soient bien dorés.", duration: 12 },
      ],
      tips: ["Plus la pâte est fine, meilleure elle est"],
      variations: ["Tarte flambée chèvre-miel", "Version végétarienne avec champignons"],
      nutritionEstimate: { calories: 450, proteins: 14, carbs: 42, fats: 26 },
    },
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  await prisma.recipe.deleteMany();
  await prisma.meal.deleteMany();

  for (const mealData of meals) {
    const { recipe, ...mealFields } = mealData;

    const meal = await prisma.meal.create({
      data: {
        ...mealFields,
        season: mealFields.season as never,
        category: mealFields.category as never,
        difficulty: mealFields.difficulty as never,
        budget: mealFields.budget as never,
        recipe: {
          create: {
            intro: recipe.intro,
            steps: recipe.steps,
            tips: recipe.tips,
            variations: recipe.variations,
            nutritionEstimate: recipe.nutritionEstimate ?? null,
            generatedByAI: false,
          },
        },
      },
    });

    console.log(`  ✅ ${meal.name}`);
  }

  // Initialiser les settings par défaut
  await prisma.settings.upsert({
    where: { id: "singleton" },
    update: {},
    create: {
      id: "singleton",
      adultsCount: 2,
      childrenCount: 0,
      defaultDays: [1, 2, 3, 4, 5, 6, 0],
      defaultMealType: "DINNER",
      defaultBudget: "NORMAL",
      defaultAmbiance: "BALANCED",
      vegetarianOverride: false,
      dbRatio: 0.7,
    },
  });

  console.log(`\n🎉 ${meals.length} repas seedés avec leurs recettes complètes !`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
