import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─────────────────────────────────────────────
// REPAS FAMILIERS (isFamiliar: true)
// Ce que la famille connaît et aime
// ─────────────────────────────────────────────
const familiarMeals = [
  {
    name: "Galettes sarrasin",
    category: "PIZZA_TART", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "MEDIUM",
    prepTime: 10, cookTime: 25, servings: 4, estimatedCost: 7, isFamiliar: true,
    tags: ["breton", "convivial", "végé"],
    ingredients: [
      { name: "farine de sarrasin", quantity: 250, unit: "g" },
      { name: "oeuf", quantity: 1, unit: "" },
      { name: "lait", quantity: 500, unit: "ml" },
      { name: "sel", quantity: 1, unit: "cc" },
      { name: "beurre", quantity: 20, unit: "g" },
    ],
    recipe: {
      intro: "Des galettes bretonnes authentiques au sarrasin. Chacun garnit la sienne à table — jambon-oeuf-fromage ou végétarienne.",
      steps: [
        { stepNumber: 1, description: "Mélanger farine, oeuf, sel. Ajouter le lait progressivement pour obtenir une pâte lisse. Laisser reposer 1h (ou la veille).", duration: 5 },
        { stepNumber: 2, description: "Cuire les galettes dans une crêpière beurrée sur feu moyen-vif, 2 min par côté.", duration: 20 },
        { stepNumber: 3, description: "Garnir avec les ingrédients choisis (jambon, oeuf, fromage, champignons, etc.) et plier en carré.", duration: 5 },
      ],
      tips: ["Préparer la pâte la veille pour plus de goût", "Entrée suggérée : salade verte ou soupe", "Proposer différentes garnitures à table"],
      variations: ["Complète (jambon-oeuf-fromage)", "Végétarienne (champignons-chèvre-épinards)", "Au saumon fumé et crème fraîche"],
      nutritionEstimate: { calories: 280, proteins: 10, carbs: 38, fats: 10 },
    },
  },
  {
    name: "Pâtes au fromage râpé",
    category: "PASTA", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 5, cookTime: 15, servings: 4, estimatedCost: 4, isFamiliar: true,
    tags: ["rapide", "enfants", "simple"],
    ingredients: [
      { name: "pâtes (spaghetti ou penne)", quantity: 400, unit: "g" },
      { name: "fromage râpé (gruyère)", quantity: 100, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Le repas de secours par excellence. Rapide, apprécié de tous, à personaliser selon les envies.",
      steps: [
        { stepNumber: 1, description: "Cuire les pâtes al dente dans l'eau bouillante salée.", duration: 12 },
        { stepNumber: 2, description: "Égoutter en gardant un peu d'eau de cuisson. Ajouter beurre et fromage. Bien mélanger.", duration: 3 },
      ],
      tips: ["Entrée suggérée : salade verte ou quelques tomates cerises", "Ajouter une noisette de beurre et du poivre noir fraîchement moulu"],
      variations: ["Avec du parmesan et de l'huile d'olive", "Avec une sauce tomate maison express"],
      nutritionEstimate: { calories: 420, proteins: 15, carbs: 68, fats: 11 },
    },
  },
  {
    name: "Quiche lardons courgette",
    category: "PIZZA_TART", foodMode: "MEAT", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 20, cookTime: 35, servings: 6, estimatedCost: 9, isFamiliar: true,
    tags: ["four", "familial", "pratique"],
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "" },
      { name: "lardons fumés", quantity: 200, unit: "g" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "crème fraîche", quantity: 20, unit: "cl" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "Une quiche maison copieuse et savoureuse. Peut se préparer la veille.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four 180°C. Foncer un moule avec la pâte.", duration: 5 },
        { stepNumber: 2, description: "Faire revenir les lardons. Couper la courgette en rondelles et faire sauter 5 min.", duration: 10 },
        { stepNumber: 3, description: "Battre oeufs + crème, sel, poivre. Verser sur la garniture. Parsemer de gruyère.", duration: 5 },
        { stepNumber: 4, description: "Cuire 35 min jusqu'à ce que la quiche soit dorée.", duration: 35 },
      ],
      tips: ["Servir avec une salade verte", "Se mange froide le lendemain"],
      variations: ["Quiche lorraine classique sans courgette", "Ajouter des champignons"],
      nutritionEstimate: { calories: 380, proteins: 16, carbs: 22, fats: 28 },
    },
  },
  {
    name: "Rôti de porc aux légumes",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 15, cookTime: 80, servings: 4, estimatedCost: 16, isFamiliar: true,
    tags: ["four", "dominical", "classique"],
    ingredients: [
      { name: "rôti de porc (filet ou épaule)", quantity: 1000, unit: "g" },
      { name: "carottes", quantity: 3, unit: "" },
      { name: "pommes de terre", quantity: 600, unit: "g" },
      { name: "oignons", quantity: 2, unit: "" },
      { name: "ail", quantity: 3, unit: "gousses" },
      { name: "huile d'olive", quantity: 2, unit: "cs" },
      { name: "thym et laurier", quantity: 1, unit: "bouquet" },
    ],
    recipe: {
      intro: "Le grand classique du dimanche. Simple à préparer, délicieux avec les légumes confits autour.",
      steps: [
        { stepNumber: 1, description: "Préchauffer le four 200°C. Ficeler le rôti si nécessaire. Saisir 5 min à la cocotte dans l'huile pour colorer.", duration: 8 },
        { stepNumber: 2, description: "Disposer les légumes coupés autour. Ajouter ail, herbes, sel, poivre et un verre d'eau.", duration: 7 },
        { stepNumber: 3, description: "Cuire 70-80 min en arrosant toutes les 20 min.", duration: 80 },
        { stepNumber: 4, description: "Laisser reposer 10 min avant de trancher.", duration: 10 },
      ],
      tips: ["Entrée suggérée : salade verte ou avocat vinaigrette", "Compter 20 min par 500g de viande"],
      variations: ["Avec champignons et crème fraîche", "Rôti de porc à la moutarde"],
      nutritionEstimate: { calories: 480, proteins: 42, carbs: 28, fats: 20 },
    },
  },
  {
    name: "Côtes de porc poêlées",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 5, cookTime: 15, servings: 4, estimatedCost: 12, isFamiliar: true,
    tags: ["rapide", "classique", "poêle"],
    ingredients: [
      { name: "côtes de porc", quantity: 4, unit: "" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "huile", quantity: 1, unit: "cs" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
      { name: "herbes de Provence", quantity: 1, unit: "cc" },
    ],
    recipe: {
      intro: "Les côtes de porc poêlées, rapides et savoureuses. Le repas pratique de la semaine.",
      steps: [
        { stepNumber: 1, description: "Sortir les côtes 15 min avant. Assaisonner sel, poivre, herbes.", duration: 2 },
        { stepNumber: 2, description: "Faire chauffer poêle avec beurre + huile à feu vif. Cuire 6-7 min par côté.", duration: 15 },
        { stepNumber: 3, description: "Laisser reposer 2 min avant de servir.", duration: 2 },
      ],
      tips: ["Accompagnement : purée maison ou haricots verts + riz", "Entrée : salade tomate ou soupe"],
      variations: ["Avec sauce moutarde", "Marinées au miel-soja avant cuisson"],
      nutritionEstimate: { calories: 380, proteins: 36, carbs: 0, fats: 25 },
    },
  },
  {
    name: "Poulet sauté aux légumes",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 10, cookTime: 30, servings: 4, estimatedCost: 14, isFamiliar: true,
    tags: ["classique", "équilibré", "familial"],
    ingredients: [
      { name: "hauts de cuisse de poulet", quantity: 800, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "ail", quantity: 2, unit: "gousses" },
      { name: "bouillon de volaille", quantity: 200, unit: "ml" },
    ],
    recipe: {
      intro: "Le poulet sauté aux légumes, un incontournable de la semaine. Adaptable avec les légumes du moment.",
      steps: [
        { stepNumber: 1, description: "Faire dorer les morceaux de poulet dans l'huile 8 min. Réserver.", duration: 10 },
        { stepNumber: 2, description: "Faire revenir oignon et ail. Ajouter les légumes coupés, saisir 5 min.", duration: 8 },
        { stepNumber: 3, description: "Remettre le poulet, ajouter le bouillon. Mijoter à couvert 20 min.", duration: 22 },
      ],
      tips: ["Servir avec du riz ou des pâtes", "Entrée suggérée : salade ou potage"],
      variations: ["Poulet à la crème et champignons", "Poulet basquaise avec poivrons et tomates"],
      nutritionEstimate: { calories: 380, proteins: 38, carbs: 12, fats: 18 },
    },
  },
  {
    name: "Nuggets maison + frites",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 25, cookTime: 25, servings: 4, estimatedCost: 12, isFamiliar: true,
    tags: ["enfants", "fun", "croustillant"],
    ingredients: [
      { name: "blancs de poulet", quantity: 600, unit: "g" },
      { name: "chapelure", quantity: 150, unit: "g" },
      { name: "oeufs", quantity: 2, unit: "" },
      { name: "farine", quantity: 50, unit: "g" },
      { name: "pommes de terre pour frites", quantity: 800, unit: "g" },
      { name: "huile de friture", quantity: 1, unit: "litre" },
    ],
    recipe: {
      intro: "Des nuggets dorés et croustillants faits maison, avec des vraies frites. Un régal pour les enfants.",
      steps: [
        { stepNumber: 1, description: "Couper le poulet en morceaux. Paner : farine → oeuf battu → chapelure.", duration: 15 },
        { stepNumber: 2, description: "Éplucher les pommes de terre, couper en frites. Rincer, sécher.", duration: 10 },
        { stepNumber: 3, description: "Frire les frites (double cuisson : 160°C puis 180°C). Frire les nuggets à 170°C, 4 min.", duration: 20 },
      ],
      tips: ["Servir avec ketchup maison", "Les nuggets peuvent aussi cuire au four à 200°C 20 min"],
      variations: ["Avec panure au parmesan et herbes", "Version poisson pané"],
      nutritionEstimate: { calories: 580, proteins: 34, carbs: 52, fats: 24 },
    },
  },
  {
    name: "Pizza maison",
    category: "PIZZA_TART", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "MEDIUM",
    prepTime: 30, cookTime: 15, servings: 4, estimatedCost: 9, isFamiliar: true,
    tags: ["fun", "enfants", "convivial"],
    ingredients: [
      { name: "farine T45", quantity: 500, unit: "g" },
      { name: "levure boulangère sèche", quantity: 7, unit: "g" },
      { name: "eau tiède", quantity: 300, unit: "ml" },
      { name: "sauce tomate", quantity: 200, unit: "ml" },
      { name: "mozzarella", quantity: 250, unit: "g" },
      { name: "garnitures au choix (jambon, champignons…)", quantity: 200, unit: "g" },
    ],
    recipe: {
      intro: "La pizza maison que tout le monde adore préparer ensemble. Pâte moelleuse, garnitures à volonté.",
      steps: [
        { stepNumber: 1, description: "Dissoudre la levure dans l'eau tiède. Mélanger avec farine + sel. Pétrir 8 min. Laisser lever 1h.", duration: 70 },
        { stepNumber: 2, description: "Étaler la pâte. Garnir de sauce tomate, mozzarella et ingrédients.", duration: 10 },
        { stepNumber: 3, description: "Cuire à four très chaud 230°C pendant 12 min.", duration: 12 },
      ],
      tips: ["Préparer la pâte la veille au frigo pour plus de goût", "Chaque enfant compose sa pizza"],
      variations: ["4 fromages", "Végétarienne poivrons-courgettes"],
      nutritionEstimate: { calories: 520, proteins: 20, carbs: 72, fats: 18 },
    },
  },
  {
    name: "Oeufs à la coque + mouillettes",
    category: "VEGETARIAN", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 2, cookTime: 6, servings: 4, estimatedCost: 4, isFamiliar: true,
    tags: ["rapide", "simple", "enfants"],
    ingredients: [
      { name: "oeufs frais", quantity: 8, unit: "" },
      { name: "pain de campagne", quantity: 1, unit: "tranche épaisse par personne" },
      { name: "beurre", quantity: 30, unit: "g" },
    ],
    recipe: {
      intro: "Simple, rapide et adoré de tous. Parfait pour un dîner léger ou le soir où on n'a pas le temps.",
      steps: [
        { stepNumber: 1, description: "Porter une casserole d'eau à ébullition. Plonger délicatement les oeufs. Cuire exactement 6 min.", duration: 8 },
        { stepNumber: 2, description: "Pendant ce temps, griller le pain et couper en mouillettes. Beurrer généreusement.", duration: 4 },
        { stepNumber: 3, description: "Servir les oeufs dans les coquetiers. Tremper et savourer !", duration: 1 },
      ],
      tips: ["Entrée ou accompagnement : soupe maison", "Pour des oeufs mollets : 9 min"],
      variations: ["Avec des soldiers de pain brioché", "Accompagner de fromage frais à tartiner"],
      nutritionEstimate: { calories: 220, proteins: 14, carbs: 20, fats: 10 },
    },
  },
  {
    name: "Raviolis du commerce",
    category: "PASTA", foodMode: "MEAT", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 2, cookTime: 10, servings: 4, estimatedCost: 5, isFamiliar: true,
    tags: ["express", "dépannage", "enfants"],
    ingredients: [
      { name: "raviolis frais ou en boîte", quantity: 800, unit: "g" },
      { name: "sauce tomate", quantity: 200, unit: "ml" },
      { name: "gruyère râpé", quantity: 50, unit: "g" },
    ],
    recipe: {
      intro: "Le repas dépannage assumé. Raviolis en boîte ou frais, avec une bonne sauce.",
      steps: [
        { stepNumber: 1, description: "Chauffer les raviolis selon les instructions. Ajouter la sauce tomate.", duration: 10 },
        { stepNumber: 2, description: "Servir avec du fromage râpé.", duration: 1 },
      ],
      tips: ["Dorer quelques lardons pour enrichir", "Entrée : salade verte"],
      variations: ["Gratinés au four 10 min", "Avec une sauce béchamel légère"],
      nutritionEstimate: { calories: 380, proteins: 14, carbs: 58, fats: 10 },
    },
  },
  {
    name: "Gnocchis poêlés",
    category: "PASTA", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 5, cookTime: 15, servings: 4, estimatedCost: 7, isFamiliar: true,
    tags: ["rapide", "croustillant", "végé"],
    ingredients: [
      { name: "gnocchis frais (rayon frais)", quantity: 500, unit: "g" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "fromage râpé", quantity: 80, unit: "g" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Les gnocchis poêlés dans le beurre pour une croûte dorée — bien meilleurs que cuits à l'eau !",
      steps: [
        { stepNumber: 1, description: "Faire fondre le beurre dans une grande poêle à feu vif. Ajouter les gnocchis en une couche.", duration: 2 },
        { stepNumber: 2, description: "Cuire 3-4 min sans remuer pour qu'ils dorent. Retourner et cuire encore 3 min.", duration: 8 },
        { stepNumber: 3, description: "Saler, poivrer, parsemer de fromage râpé. Servir immédiatement.", duration: 2 },
      ],
      tips: ["Ajouter des légumes sautés (épinards, champignons) pour compléter", "Entrée : salade ou soupe"],
      variations: ["Avec sauce tomate aux herbes", "Gnocchis beurre-sauge"],
      nutritionEstimate: { calories: 380, proteins: 10, carbs: 58, fats: 14 },
    },
  },
  {
    name: "Croque monsieur + salade",
    category: "SANDWICH", foodMode: "MEAT", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 10, cookTime: 12, servings: 4, estimatedCost: 6, isFamiliar: true,
    tags: ["rapide", "enfants", "gratiné"],
    ingredients: [
      { name: "pain de mie", quantity: 8, unit: "tranches" },
      { name: "jambon blanc", quantity: 4, unit: "tranches" },
      { name: "gruyère râpé", quantity: 120, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "béchamel", quantity: 150, unit: "ml" },
      { name: "salade verte", quantity: 1, unit: "" },
    ],
    recipe: {
      intro: "Le croque monsieur maison avec une vraie béchamel. Servi avec une salade — un repas complet.",
      steps: [
        { stepNumber: 1, description: "Préparer une béchamel légère (beurre + farine + lait). Assaisonner.", duration: 8 },
        { stepNumber: 2, description: "Tartiner les tranches de pain de béchamel. Garnir de jambon et fromage.", duration: 4 },
        { stepNumber: 3, description: "Passer au four gril 10-12 min jusqu'à ce que ça dore.", duration: 12 },
        { stepNumber: 4, description: "Servir avec la salade assaisonnée.", duration: 2 },
      ],
      tips: ["Ajouter un oeuf poché sur le dessus → croque madame"],
      variations: ["Croque au chèvre et miel", "Version saumon-crème fraîche"],
      nutritionEstimate: { calories: 420, proteins: 22, carbs: 38, fats: 20 },
    },
  },
  {
    name: "Salade de thon au riz",
    category: "SALAD", foodMode: "FISH", mealTypes: ["DINNER", "LUNCH"],
    season: ["SUMMER", "ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 15, cookTime: 15, servings: 4, estimatedCost: 8, isFamiliar: true,
    tags: ["été", "frais", "léger"],
    ingredients: [
      { name: "riz long grain", quantity: 200, unit: "g" },
      { name: "thon en boîte (au naturel)", quantity: 320, unit: "g" },
      { name: "tomates", quantity: 3, unit: "" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "olives noires", quantity: 50, unit: "g" },
      { name: "vinaigrette (huile+citron)", quantity: 4, unit: "cs" },
    ],
    recipe: {
      intro: "La salade de thon au riz, fraîche et complète. Parfaite en été, rapide à préparer.",
      steps: [
        { stepNumber: 1, description: "Cuire le riz selon les instructions. Laisser refroidir.", duration: 15 },
        { stepNumber: 2, description: "Couper les légumes. Égoutter le thon.", duration: 8 },
        { stepNumber: 3, description: "Mélanger tous les ingrédients. Assaisonner avec la vinaigrette.", duration: 3 },
      ],
      tips: ["Servir bien frais", "Peut se préparer à l'avance"],
      variations: ["Avec des dés d'avocat", "Version grecque avec feta et concombre"],
      nutritionEstimate: { calories: 340, proteins: 24, carbs: 42, fats: 8 },
    },
  },
  {
    name: "Saumon, riz, légumes",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 10, cookTime: 20, servings: 4, estimatedCost: 20, isFamiliar: true,
    tags: ["healthy", "équilibré", "simple"],
    ingredients: [
      { name: "pavés de saumon", quantity: 4, unit: "" },
      { name: "riz basmati", quantity: 300, unit: "g" },
      { name: "haricots verts ou brocoli", quantity: 400, unit: "g" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "cs" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Un repas équilibré et sain. Saumon, riz, légumes — le trio gagnant.",
      steps: [
        { stepNumber: 1, description: "Cuire le riz. Cuire les légumes à la vapeur ou à l'eau.", duration: 15 },
        { stepNumber: 2, description: "Cuire le saumon à la poêle avec huile d'olive, 4 min par côté.", duration: 10 },
        { stepNumber: 3, description: "Servir avec le citron pressé.", duration: 2 },
      ],
      tips: ["Entrée : avocat en deux avec vinaigrette", "Une noix de beurre sur le saumon en fin de cuisson"],
      variations: ["Saumon en papillote au four", "Avec sauce soja et gingembre"],
      nutritionEstimate: { calories: 420, proteins: 36, carbs: 42, fats: 10 },
    },
  },
  {
    name: "Tarte aux champignons",
    category: "PIZZA_TART", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 15, cookTime: 35, servings: 6, estimatedCost: 8, isFamiliar: true,
    tags: ["champignons", "végé", "four"],
    ingredients: [
      { name: "pâte feuilletée", quantity: 1, unit: "" },
      { name: "champignons de Paris", quantity: 500, unit: "g" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "crème fraîche", quantity: 20, unit: "cl" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
      { name: "ail", quantity: 2, unit: "gousses" },
    ],
    recipe: {
      intro: "Une tarte aux champignons onctueuse et parfumée. Simple et délicieuse.",
      steps: [
        { stepNumber: 1, description: "Faire revenir les champignons avec ail dans l'huile jusqu'à évaporation de l'eau.", duration: 10 },
        { stepNumber: 2, description: "Foncer un moule avec la pâte. Battre oeufs + crème. Ajouter champignons et fromage.", duration: 8 },
        { stepNumber: 3, description: "Verser l'appareil sur la pâte. Cuire 35 min à 180°C.", duration: 35 },
      ],
      tips: ["Servir avec salade verte", "Ajouter quelques lardons pour les non végétariens"],
      variations: ["Avec des champignons mélangés (pleurotes, girolles)", "Ajouter du chèvre émietté"],
      nutritionEstimate: { calories: 360, proteins: 14, carbs: 26, fats: 24 },
    },
  },
  {
    name: "Filet de lieu",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 5, cookTime: 15, servings: 4, estimatedCost: 16, isFamiliar: true,
    tags: ["poisson", "léger", "rapide"],
    ingredients: [
      { name: "filets de lieu noir", quantity: 600, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "persil frais", quantity: 4, unit: "brins" },
      { name: "sel et poivre", quantity: 1, unit: "pincée" },
    ],
    recipe: {
      intro: "Le lieu noir poêlé au beurre-citron. Rapide et sain.",
      steps: [
        { stepNumber: 1, description: "Sécher les filets. Assaisonner sel et poivre.", duration: 2 },
        { stepNumber: 2, description: "Faire fondre le beurre dans la poêle. Cuire les filets 3-4 min par côté.", duration: 10 },
        { stepNumber: 3, description: "Arroser de jus de citron et parsemer de persil.", duration: 2 },
      ],
      tips: ["Accompagnement : riz basmati + brocoli vapeur", "Entrée : salade de tomates"],
      variations: ["Avec sauce vierge (tomates, basilic, huile)", "Au four en papillote"],
      nutritionEstimate: { calories: 220, proteins: 34, carbs: 0, fats: 9 },
    },
  },
  {
    name: "Dorade royale et légumes",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["SUMMER", "ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 10, cookTime: 25, servings: 4, estimatedCost: 22, isFamiliar: true,
    tags: ["poisson", "four", "méditerranéen"],
    ingredients: [
      { name: "dorades royales", quantity: 2, unit: "(600g chacune)" },
      { name: "tomates", quantity: 3, unit: "" },
      { name: "poivrons", quantity: 2, unit: "" },
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "ail", quantity: 3, unit: "gousses" },
      { name: "huile d'olive", quantity: 3, unit: "cs" },
      { name: "thym et romarin", quantity: 1, unit: "bouquet" },
    ],
    recipe: {
      intro: "La dorade au four sur lit de légumes méditerranéens. Un plat coloré et parfumé.",
      steps: [
        { stepNumber: 1, description: "Préchauffer four 200°C. Disposer les légumes coupés dans un plat. Huiler, assaisonner.", duration: 10 },
        { stepNumber: 2, description: "Inciser les dorades 2-3 fois. Les poser sur les légumes. Huile, sel, herbes.", duration: 5 },
        { stepNumber: 3, description: "Cuire 25 min jusqu'à ce que la peau soit dorée.", duration: 25 },
      ],
      tips: ["Entrée : avocat aux crevettes", "Demander au poissonnier d'écailler et vider"],
      variations: ["Avec olives et câpres", "En papillote individuelle"],
      nutritionEstimate: { calories: 340, proteins: 40, carbs: 12, fats: 14 },
    },
  },
  {
    name: "Filet de julienne, riz et légumes",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 10, cookTime: 20, servings: 4, estimatedCost: 18, isFamiliar: true,
    tags: ["poisson", "léger", "équilibré"],
    ingredients: [
      { name: "filets de julienne (merlu)", quantity: 600, unit: "g" },
      { name: "riz basmati", quantity: 300, unit: "g" },
      { name: "carottes", quantity: 3, unit: "" },
      { name: "haricots verts", quantity: 300, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "citron", quantity: 1, unit: "" },
    ],
    recipe: {
      intro: "La julienne (merlu) est un poisson blanc délicat, parfait poêlé avec riz et légumes vapeur.",
      steps: [
        { stepNumber: 1, description: "Cuire riz et légumes en parallèle.", duration: 15 },
        { stepNumber: 2, description: "Cuire les filets de julienne au beurre 3-4 min par côté. Citronner.", duration: 10 },
        { stepNumber: 3, description: "Servir avec le riz et les légumes.", duration: 2 },
      ],
      tips: ["Entrée : salade verte avec vinaigrette citron", "Poisson très délicat, ne pas surcuire"],
      variations: ["En papillote avec fenouil", "Sauce hollandaise allégée"],
      nutritionEstimate: { calories: 320, proteins: 36, carbs: 38, fats: 6 },
    },
  },
  {
    name: "Poisson pané + légumes frites",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 10, cookTime: 20, servings: 4, estimatedCost: 12, isFamiliar: true,
    tags: ["enfants", "croustillant", "classique"],
    ingredients: [
      { name: "poisson pané (surgelé ou frais)", quantity: 8, unit: "filets" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "huile de friture", quantity: 1, unit: "litre" },
      { name: "légumes au choix (petits pois, haricots)", quantity: 400, unit: "g" },
    ],
    recipe: {
      intro: "Le poisson pané avec des frites maison — adoré des enfants et rapide à faire.",
      steps: [
        { stepNumber: 1, description: "Cuire les frites (double friture). Cuire les légumes vapeur.", duration: 15 },
        { stepNumber: 2, description: "Cuire le poisson pané à la poêle 3-4 min par côté ou au four.", duration: 12 },
        { stepNumber: 3, description: "Servir avec de la moutarde ou une sauce tartare maison.", duration: 2 },
      ],
      tips: ["Le poisson pané Picard est excellent pour dépanner"],
      variations: ["Avec purée maison à la place des frites", "Sauce yaourt-herbes"],
      nutritionEstimate: { calories: 480, proteins: 26, carbs: 52, fats: 18 },
    },
  },
  {
    name: "Lentilles aux saucisses",
    category: "STEW", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 10, cookTime: 35, servings: 4, estimatedCost: 8, isFamiliar: true,
    tags: ["hivernal", "réconfortant", "économique"],
    ingredients: [
      { name: "lentilles vertes", quantity: 300, unit: "g" },
      { name: "saucisses de Strasbourg ou Morteau", quantity: 4, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "ail", quantity: 2, unit: "gousses" },
      { name: "bouillon", quantity: 700, unit: "ml" },
      { name: "moutarde", quantity: 1, unit: "cs" },
    ],
    recipe: {
      intro: "Le plat d'hiver réconfortant par excellence. Lentilles fondantes et saucisses généreuses.",
      steps: [
        { stepNumber: 1, description: "Faire revenir oignon, ail et carottes. Ajouter les lentilles et le bouillon.", duration: 8 },
        { stepNumber: 2, description: "Cuire les lentilles 25-30 min. Ajouter les saucisses les 15 dernières minutes.", duration: 30 },
        { stepNumber: 3, description: "Rectifier avec la moutarde et assaisonner.", duration: 2 },
      ],
      tips: ["Entrée : salade d'endives ou soupe de légumes", "Se bonifie le lendemain"],
      variations: ["Avec saucisson à cuire", "Lentilles au lard fumé"],
      nutritionEstimate: { calories: 480, proteins: 28, carbs: 48, fats: 18 },
    },
  },
  {
    name: "Quiche lorraine",
    category: "PIZZA_TART", foodMode: "MEAT", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 20, cookTime: 35, servings: 6, estimatedCost: 8, isFamiliar: true,
    tags: ["classique", "four", "familial"],
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "" },
      { name: "lardons fumés", quantity: 200, unit: "g" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "crème fraîche épaisse", quantity: 200, unit: "ml" },
      { name: "lait", quantity: 100, unit: "ml" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "La quiche lorraine classique, toujours réussie.",
      steps: [
        { stepNumber: 1, description: "Préchauffer 180°C. Foncer le moule avec la pâte.", duration: 5 },
        { stepNumber: 2, description: "Faire revenir les lardons. Battre oeufs + crème + lait. Assaisonner.", duration: 8 },
        { stepNumber: 3, description: "Répartir lardons, verser l'appareil, parsemer de gruyère. Cuire 35 min.", duration: 35 },
      ],
      tips: ["Servir avec salade verte", "Pré-cuire la pâte 10 min à blanc"],
      variations: ["Quiche aux poireaux", "Avec des champignons"],
      nutritionEstimate: { calories: 420, proteins: 16, carbs: 24, fats: 30 },
    },
  },
  {
    name: "Quiche aux légumes",
    category: "PIZZA_TART", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 20, cookTime: 35, servings: 6, estimatedCost: 7, isFamiliar: true,
    tags: ["végé", "four", "pratique"],
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "" },
      { name: "poireaux ou courgettes ou épinards", quantity: 400, unit: "g" },
      { name: "oeufs", quantity: 3, unit: "" },
      { name: "crème fraîche", quantity: 200, unit: "ml" },
      { name: "gruyère râpé", quantity: 80, unit: "g" },
    ],
    recipe: {
      intro: "La quiche végétarienne adaptable selon les légumes du moment.",
      steps: [
        { stepNumber: 1, description: "Faire revenir les légumes jusqu'à ce qu'ils soient tendres.", duration: 10 },
        { stepNumber: 2, description: "Foncer le moule. Battre oeufs + crème. Ajouter les légumes et le fromage.", duration: 8 },
        { stepNumber: 3, description: "Verser l'appareil. Cuire 35 min à 180°C.", duration: 35 },
      ],
      tips: ["Servir avec salade verte", "S'adapte aux légumes disponibles"],
      variations: ["Quiche poireaux-chèvre", "Quiche épinards-ricotta"],
      nutritionEstimate: { calories: 360, proteins: 12, carbs: 22, fats: 26 },
    },
  },
  {
    name: "Salade tomate mozza + féculent",
    category: "SALAD", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["SUMMER"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 10, cookTime: 10, servings: 4, estimatedCost: 9, isFamiliar: true,
    tags: ["été", "frais", "italien"],
    ingredients: [
      { name: "tomates", quantity: 4, unit: "" },
      { name: "mozzarella", quantity: 250, unit: "g" },
      { name: "basilic frais", quantity: 1, unit: "bouquet" },
      { name: "huile d'olive", quantity: 3, unit: "cs" },
      { name: "pâtes ou semoule", quantity: 200, unit: "g" },
    ],
    recipe: {
      intro: "La salade caprese avec un féculent pour avoir faim — la salade d'été parfaite.",
      steps: [
        { stepNumber: 1, description: "Cuire les pâtes ou la semoule. Refroidir.", duration: 10 },
        { stepNumber: 2, description: "Trancher tomates et mozzarella. Disposer en alternant.", duration: 5 },
        { stepNumber: 3, description: "Assaisonner d'huile d'olive, sel, basilic frais. Ajouter le féculent.", duration: 3 },
      ],
      tips: ["Mettre la salade au frais 30 min avant de servir", "Du bon vinaigre balsamique en filet"],
      variations: ["Avec des olives noires", "Ajouter des dés d'avocat"],
      nutritionEstimate: { calories: 380, proteins: 16, carbs: 38, fats: 18 },
    },
  },
  {
    name: "Salade améliorée",
    category: "SALAD", foodMode: "VEGETARIAN", mealTypes: ["DINNER", "LUNCH"],
    season: ["SUMMER", "ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 15, cookTime: 0, servings: 4, estimatedCost: 7, isFamiliar: true,
    tags: ["été", "frais", "composée"],
    ingredients: [
      { name: "salade (mesclun ou batavia)", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 200, unit: "g" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "oeufs durs", quantity: 4, unit: "" },
      { name: "croûtons ou fromage", quantity: 1, unit: "poignée" },
      { name: "vinaigrette maison", quantity: 4, unit: "cs" },
    ],
    recipe: {
      intro: "La grande salade composée du soir, copieuse et fraîche. Personnalisable à l'infini.",
      steps: [
        { stepNumber: 1, description: "Cuire les oeufs durs 10 min. Refroidir et écaler.", duration: 12 },
        { stepNumber: 2, description: "Préparer les légumes. Préparer la vinaigrette.", duration: 5 },
        { stepNumber: 3, description: "Assembler la salade au moment de servir.", duration: 3 },
      ],
      tips: ["Ajouter des protéines : thon, poulet froid, dés de jambon", "Croûtons ail maison pour plus de croquant"],
      variations: ["Salade niçoise (thon, olives, anchois)", "Salade César (poulet, parmesan, sauce crémeuse)"],
      nutritionEstimate: { calories: 240, proteins: 14, carbs: 14, fats: 14 },
    },
  },
  {
    name: "Soupe maison améliorée",
    category: "SOUP", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 15, cookTime: 30, servings: 4, estimatedCost: 5, isFamiliar: true,
    tags: ["hivernal", "réconfortant", "maison"],
    ingredients: [
      { name: "légumes de saison (poireaux, carottes, courgettes)", quantity: 800, unit: "g" },
      { name: "pomme de terre", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon de légumes", quantity: 1, unit: "litre" },
      { name: "crème fraîche", quantity: 2, unit: "cs" },
      { name: "pain grillé", quantity: 4, unit: "tranches" },
    ],
    recipe: {
      intro: "La soupe maison réconfortante, variée selon ce qu'il y a au frigo. Servie avec du pain grillé.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon. Ajouter tous les légumes coupés.", duration: 8 },
        { stepNumber: 2, description: "Couvrir de bouillon. Cuire 25 min.", duration: 25 },
        { stepNumber: 3, description: "Mixer ou laisser en morceaux selon préférence. Ajouter la crème.", duration: 3 },
      ],
      tips: ["Accompagner de pain grillé avec du fromage fondu", "Ajouter des lardons ou des croûtons"],
      variations: ["Velouté de poireaux pomme de terre", "Soupe minestrone avec pâtes"],
      nutritionEstimate: { calories: 180, proteins: 5, carbs: 28, fats: 5 },
    },
  },
  {
    name: "Risotto",
    category: "RICE_GRAINS", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 10, cookTime: 30, servings: 4, estimatedCost: 10, isFamiliar: true,
    tags: ["crémeux", "végé", "réconfortant"],
    ingredients: [
      { name: "riz arborio", quantity: 320, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "vin blanc", quantity: 100, unit: "ml" },
      { name: "bouillon chaud (légumes ou volaille)", quantity: 1200, unit: "ml" },
      { name: "parmesan", quantity: 60, unit: "g" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "garniture au choix (champignons, asperges, parmesan)", quantity: 300, unit: "g" },
    ],
    recipe: {
      intro: "Le risotto maison, crémeux et réconfortant. La clé : remuer et ajouter le bouillon louche par louche.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon dans le beurre. Ajouter le riz et nacrer 2 min.", duration: 5 },
        { stepNumber: 2, description: "Déglacer au vin blanc. Ajouter le bouillon chaud louche par louche en remuant constamment.", duration: 22 },
        { stepNumber: 3, description: "Hors du feu, ajouter beurre + parmesan (mantecatura). Incorporer la garniture.", duration: 3 },
      ],
      tips: ["Entrée : salade verte ou vitello tonnato", "Le bouillon doit toujours être chaud"],
      variations: ["Risotto champignons", "Risotto asperges-citron", "Risotto poireaux-chèvre"],
      nutritionEstimate: { calories: 460, proteins: 12, carbs: 68, fats: 14 },
    },
  },
];

// ─────────────────────────────────────────────
// RECETTES ÉLABORÉES (isFamiliar: false)
// Sorties de zone de confort — blogs et nouvelles découvertes
// ─────────────────────────────────────────────
const novelMeals = [
  {
    name: "Poulet piccata citron câpres",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 15, cookTime: 20, servings: 4, estimatedCost: 16,
    isFamiliar: false, sourceBlog: "lacerisesurlemaillot.fr",
    tags: ["italien", "élaboré", "frais"],
    ingredients: [
      { name: "escalopes de poulet", quantity: 600, unit: "g" },
      { name: "câpres", quantity: 40, unit: "g" },
      { name: "citron (jus et zeste)", quantity: 2, unit: "" },
      { name: "vin blanc sec", quantity: 100, unit: "ml" },
      { name: "bouillon de volaille", quantity: 150, unit: "ml" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "farine", quantity: 40, unit: "g" },
      { name: "persil plat", quantity: 4, unit: "brins" },
    ],
    recipe: {
      intro: "Un grand classique italo-américain : escalopes de poulet dorées dans une sauce acidulée au citron et aux câpres. Élégant, rapide, inoubliable.",
      steps: [
        { stepNumber: 1, description: "Aplatir les escalopes entre deux feuilles de film. Saler, poivrer et fariner légèrement.", duration: 8 },
        { stepNumber: 2, description: "Dorer les escalopes 2-3 min par côté dans beurre + huile. Réserver.", duration: 8 },
        { stepNumber: 3, description: "Dans la même poêle, déglacer au vin blanc. Réduire 2 min.", duration: 4 },
        { stepNumber: 4, description: "Ajouter bouillon, jus de citron et câpres. Réduire 3 min. Monter avec du beurre froid.", duration: 6 },
        { stepNumber: 5, description: "Remettre le poulet dans la sauce. Parsemer de persil et zeste de citron.", duration: 2 },
      ],
      tips: ["Servir avec des linguine ou des pommes de terre sautées", "Entrée : burrata sur roquette"],
      variations: ["Avec des câpres marinées aux herbes", "Piccata de veau"],
      nutritionEstimate: { calories: 360, proteins: 38, carbs: 10, fats: 18 },
    },
  },
  {
    name: "Poulet aux poireaux et crème",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "NORMAL", difficulty: "EASY",
    prepTime: 15, cookTime: 25, servings: 4, estimatedCost: 14,
    isFamiliar: false, sourceBlog: "lacerisesurlemaillot.fr",
    tags: ["hivernal", "crémeux", "express"],
    ingredients: [
      { name: "filets de poulet", quantity: 600, unit: "g" },
      { name: "poireaux", quantity: 3, unit: "" },
      { name: "crème fraîche liquide", quantity: 200, unit: "ml" },
      { name: "moutarde de Dijon", quantity: 1, unit: "cs" },
      { name: "ail", quantity: 2, unit: "gousses" },
      { name: "vin blanc", quantity: 100, unit: "ml" },
      { name: "beurre", quantity: 20, unit: "g" },
    ],
    recipe: {
      intro: "Un poulet express aux poireaux fondants nappé d'une sauce crémeuse à la moutarde. Prêt en 40 minutes.",
      steps: [
        { stepNumber: 1, description: "Émincer les blancs de poireaux. Couper le poulet en lamelles.", duration: 10 },
        { stepNumber: 2, description: "Faire fondre les poireaux dans le beurre avec l'ail, 10 min.", duration: 12 },
        { stepNumber: 3, description: "Ajouter le poulet, faire dorer. Déglacer au vin blanc.", duration: 8 },
        { stepNumber: 4, description: "Incorporer crème et moutarde. Mijoter 5 min. Assaisonner.", duration: 6 },
      ],
      tips: ["Servir avec du riz ou des tagliatelles fraîches", "Entrée : velouté de légumes"],
      variations: ["Avec du curry en poudre", "Remplacer les poireaux par des champignons"],
      nutritionEstimate: { calories: 380, proteins: 40, carbs: 8, fats: 20 },
    },
  },
  {
    name: "Tajine d'agneau aux pruneaux",
    category: "STEW", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "SPLURGE", difficulty: "MEDIUM",
    prepTime: 20, cookTime: 90, servings: 4, estimatedCost: 24,
    isFamiliar: false,
    tags: ["marocain", "festif", "épicé"],
    ingredients: [
      { name: "épaule d'agneau en morceaux", quantity: 1000, unit: "g" },
      { name: "pruneaux dénoyautés", quantity: 200, unit: "g" },
      { name: "oignons", quantity: 2, unit: "" },
      { name: "miel", quantity: 2, unit: "cs" },
      { name: "cannelle", quantity: 1, unit: "bâton" },
      { name: "ras-el-hanout", quantity: 2, unit: "cs" },
      { name: "amandes effilées", quantity: 50, unit: "g" },
      { name: "coriandre fraîche", quantity: 4, unit: "brins" },
    ],
    recipe: {
      intro: "Un tajine doux et parfumé qui embaume la maison. Les pruneaux apportent une douceur inattendue à l'agneau braisé.",
      steps: [
        { stepNumber: 1, description: "Faire dorer les morceaux d'agneau sur toutes les faces. Réserver.", duration: 12 },
        { stepNumber: 2, description: "Faire revenir les oignons éminces. Ajouter le ras-el-hanout et la cannelle.", duration: 5 },
        { stepNumber: 3, description: "Remettre l'agneau. Ajouter 200ml d'eau. Couvrir et mijoter 1h à feu doux.", duration: 65 },
        { stepNumber: 4, description: "Ajouter pruneaux et miel. Cuire 20 min de plus.", duration: 20 },
        { stepNumber: 5, description: "Parsemer d'amandes grillées et de coriandre fraîche.", duration: 3 },
      ],
      tips: ["Servir avec de la semoule et du pain khobz", "Entrée : houmous maison et crudités"],
      variations: ["Avec des abricots secs à la place des pruneaux", "Tajine de poulet au citron confit"],
      nutritionEstimate: { calories: 520, proteins: 42, carbs: 28, fats: 26 },
    },
  },
  {
    name: "Tartare de saumon avocat sésame",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["SUMMER", "ALL_YEAR"], budget: "SPLURGE", difficulty: "MEDIUM",
    prepTime: 20, cookTime: 0, servings: 4, estimatedCost: 22,
    isFamiliar: false,
    tags: ["frais", "japonais", "élégant"],
    ingredients: [
      { name: "saumon frais (qualité sashimi)", quantity: 400, unit: "g" },
      { name: "avocat mûr", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "cs" },
      { name: "huile de sésame", quantity: 1, unit: "cc" },
      { name: "citron vert", quantity: 1, unit: "" },
      { name: "gingembre frais râpé", quantity: 1, unit: "cc" },
      { name: "graines de sésame", quantity: 2, unit: "cs" },
      { name: "ciboulette", quantity: 1, unit: "bouquet" },
    ],
    recipe: {
      intro: "Un tartare frais et élégant qui mêle le fondant du saumon et l'onctuosité de l'avocat avec une touche asiatique.",
      steps: [
        { stepNumber: 1, description: "Couper le saumon en petits dés réguliers de 5mm.", duration: 10 },
        { stepNumber: 2, description: "Préparer la marinade : soja, huile de sésame, citron vert, gingembre.", duration: 3 },
        { stepNumber: 3, description: "Mélanger le saumon avec la marinade. Réserver 10 min au frais.", duration: 10 },
        { stepNumber: 4, description: "Dresser en cercle : lit d'avocat écrasé, tartare de saumon dessus. Sésame + ciboulette.", duration: 5 },
      ],
      tips: ["Servir avec des chips de wonton ou pain grillé", "Entrée de choix pour un repas festif"],
      variations: ["Tartare de thon à la mangue", "Avec de l'huile truffée"],
      nutritionEstimate: { calories: 320, proteins: 28, carbs: 4, fats: 22 },
    },
  },
  {
    name: "Velouté butternut lait de coco",
    category: "SOUP", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "CHEAP", difficulty: "EASY",
    prepTime: 15, cookTime: 30, servings: 4, estimatedCost: 8,
    isFamiliar: false, sourceBlog: "claireaumatcha.blogspot.com",
    tags: ["végé", "doux", "hivernal"],
    ingredients: [
      { name: "courge butternut", quantity: 1000, unit: "g" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gingembre frais", quantity: 2, unit: "cm" },
      { name: "curcuma", quantity: 1, unit: "cc" },
      { name: "bouillon de légumes", quantity: 400, unit: "ml" },
      { name: "graines de courge", quantity: 2, unit: "cs" },
    ],
    recipe: {
      intro: "Un velouté tout doux et légèrement exotique. La butternut s'associe merveilleusement avec le lait de coco.",
      steps: [
        { stepNumber: 1, description: "Faire revenir l'oignon et le gingembre râpé avec le curcuma.", duration: 5 },
        { stepNumber: 2, description: "Ajouter la butternut coupée en dés et le bouillon. Cuire 25 min.", duration: 28 },
        { stepNumber: 3, description: "Mixer avec le lait de coco jusqu'à consistance lisse.", duration: 3 },
        { stepNumber: 4, description: "Servir avec des graines de courge grillées et un filet d'huile de sésame.", duration: 2 },
      ],
      tips: ["Accompagner de pain grillé ou de croûtons", "Ajouter du piment d'Espelette pour du piquant"],
      variations: ["Avec de la coriandre fraîche", "Ajouter du curry plutôt que le curcuma"],
      nutritionEstimate: { calories: 220, proteins: 4, carbs: 28, fats: 11 },
    },
  },
  {
    name: "Gnocchis poêlés beurre de sauge",
    category: "PASTA", foodMode: "VEGETARIAN", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 10, cookTime: 15, servings: 4, estimatedCost: 10,
    isFamiliar: false, sourceBlog: "ondinecheznanou.blogspot.com",
    tags: ["italien", "élaboré", "noisette"],
    ingredients: [
      { name: "gnocchis frais maison ou du commerce", quantity: 500, unit: "g" },
      { name: "beurre doux", quantity: 80, unit: "g" },
      { name: "sauge fraîche", quantity: 12, unit: "feuilles" },
      { name: "parmesan", quantity: 60, unit: "g" },
      { name: "noix", quantity: 40, unit: "g" },
      { name: "poivre noir", quantity: 1, unit: "mouture généreuse" },
    ],
    recipe: {
      intro: "Les gnocchis poêlés au beurre de sauge noisette — une préparation italienne simple qui révèle la profondeur de saveurs du beurre bien cuit.",
      steps: [
        { stepNumber: 1, description: "Faire dorer les gnocchis dans une poêle sèche ou légèrement huilée, 3 min par côté.", duration: 8 },
        { stepNumber: 2, description: "Dans une autre poêle, faire chauffer le beurre jusqu'à ce qu'il mousse et commence à dorer (couleur noisette).", duration: 4 },
        { stepNumber: 3, description: "Ajouter les feuilles de sauge dans le beurre noisette — elles vont croustiller en 30 secondes.", duration: 1 },
        { stepNumber: 4, description: "Napper les gnocchis de beurre de sauge. Parsemer de parmesan râpé et noix concassées.", duration: 2 },
      ],
      tips: ["Le beurre noisette a une fenêtre courte : surveiller et retirer du feu à temps", "Entrée : burrata ou salade de roquette"],
      variations: ["Ajouter des épinards sautés", "Avec des champignons poêlés"],
      nutritionEstimate: { calories: 480, proteins: 14, carbs: 52, fats: 26 },
    },
  },
  {
    name: "Poulet aux olives et citron confit",
    category: "MEAT", foodMode: "MEAT", mealTypes: ["DINNER"],
    season: ["ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 15, cookTime: 45, servings: 4, estimatedCost: 16,
    isFamiliar: false,
    tags: ["méditerranéen", "citron confit", "olives"],
    ingredients: [
      { name: "morceaux de poulet (cuisse + haut de cuisse)", quantity: 1200, unit: "g" },
      { name: "citron confit au sel", quantity: 1, unit: "" },
      { name: "olives vertes", quantity: 100, unit: "g" },
      { name: "oignons", quantity: 2, unit: "" },
      { name: "ail", quantity: 4, unit: "gousses" },
      { name: "cumin", quantity: 1, unit: "cc" },
      { name: "coriandre en poudre", quantity: 1, unit: "cc" },
      { name: "bouillon de volaille", quantity: 200, unit: "ml" },
    ],
    recipe: {
      intro: "Un plat parfumé aux notes méditerranéennes. Le citron confit apporte une saveur unique, légèrement fermentée et intense.",
      steps: [
        { stepNumber: 1, description: "Faire dorer les morceaux de poulet sur toutes les faces. Réserver.", duration: 12 },
        { stepNumber: 2, description: "Faire revenir oignons et ail avec les épices.", duration: 6 },
        { stepNumber: 3, description: "Ajouter le poulet, le bouillon, les olives et la peau du citron confit émincée.", duration: 5 },
        { stepNumber: 4, description: "Mijoter à couvert 35 min. Rectifier l'assaisonnement.", duration: 35 },
      ],
      tips: ["Servir avec de la semoule ou du riz", "Entrée : houmous et pain pita grillé"],
      variations: ["Avec des artichauts en conserve", "Version avec de la harissa"],
      nutritionEstimate: { calories: 420, proteins: 44, carbs: 6, fats: 24 },
    },
  },
  {
    name: "Gratin de poireaux au saumon fumé",
    category: "FISH", foodMode: "FISH", mealTypes: ["DINNER"],
    season: ["WINTER", "ALL_YEAR"], budget: "NORMAL", difficulty: "MEDIUM",
    prepTime: 20, cookTime: 30, servings: 4, estimatedCost: 18,
    isFamiliar: false, sourceBlog: "ondinecheznanou.blogspot.com",
    tags: ["gratiné", "poisson", "hivernal"],
    ingredients: [
      { name: "poireaux", quantity: 4, unit: "" },
      { name: "saumon fumé", quantity: 200, unit: "g" },
      { name: "crème fraîche liquide", quantity: 250, unit: "ml" },
      { name: "gruyère râpé", quantity: 100, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "oeuf", quantity: 1, unit: "" },
      { name: "aneth frais", quantity: 4, unit: "brins" },
    ],
    recipe: {
      intro: "Un gratin délicat et savoureux qui marie les poireaux fondants et le fumé intense du saumon. Un plat hivernal élégant.",
      steps: [
        { stepNumber: 1, description: "Cuire les poireaux émincés dans le beurre, à couvert, 15 min.", duration: 17 },
        { stepNumber: 2, description: "Mélanger crème + oeuf + aneth. Saler légèrement (le saumon est salé).", duration: 3 },
        { stepNumber: 3, description: "Disposer poireaux et lamelles de saumon fumé dans un plat beurré. Verser l'appareil crémeux.", duration: 5 },
        { stepNumber: 4, description: "Parsemer de gruyère. Gratiner 25-30 min à 180°C.", duration: 30 },
      ],
      tips: ["Entrée : velouté de légumes", "Servir avec pain de campagne"],
      variations: ["Avec des crevettes à la place du saumon fumé", "Ajouter des champignons"],
      nutritionEstimate: { calories: 380, proteins: 28, carbs: 8, fats: 28 },
    },
  },
];

const allMeals = [...familiarMeals, ...novelMeals];

async function main() {
  console.log("🌱 Nettoyage de la BDD et re-seeding...\n");

  // Suppression dans l'ordre des dépendances
  await prisma.shoppingItem.deleteMany();
  await prisma.shoppingList.deleteMany();
  await prisma.plannedMeal.deleteMany();
  await prisma.recipe.deleteMany();
  await prisma.meal.deleteMany();

  console.log("🗑️  Anciens repas supprimés.\n");

  for (const mealData of allMeals) {
    const { recipe, ...mealFields } = mealData;

    const meal = await prisma.meal.create({
      data: {
        ...mealFields,
        season: mealFields.season as never,
        category: mealFields.category as never,
        difficulty: mealFields.difficulty as never,
        budget: mealFields.budget as never,
        foodMode: mealFields.foodMode as never,
        mealTypes: mealFields.mealTypes as never,
        isVegetarian: mealFields.foodMode === "VEGETARIAN",
        isVegan: false,
        isFish: mealFields.foodMode === "FISH",
        isCustom: true,
        recipe: {
          create: {
            intro: recipe.intro,
            steps: recipe.steps,
            tips: recipe.tips,
            variations: recipe.variations,
            nutritionEstimate: recipe.nutritionEstimate ?? null,
            generatedByAI: false,
          },
        },
      },
    });

    const badge = meal.isFamiliar ? "🏠" : "✨";
    console.log(`  ${badge} ${meal.name}`);
  }

  // Settings par défaut
  await prisma.settings.upsert({
    where: { id: "singleton" },
    update: {},
    create: {
      id: "singleton",
      adultsCount: 2,
      childrenCount: 2,
      defaultDays: [1, 2, 3, 4, 5, 6, 0],
      defaultMealType: "DINNER",
      defaultBudget: "NORMAL",
      defaultFoodMode: "MEAT",
      defaultDinnerFoodMode: "VEGETARIAN",
      festiveDays: [5, 6, 0],
      noLunchDays: [1, 2, 4, 5],
      dbRatio: 0.7,
    },
  });

  const familiar = allMeals.filter((m) => m.isFamiliar).length;
  const novel = allMeals.filter((m) => !m.isFamiliar).length;
  console.log(`\n✅ ${familiar} repas familiers 🏠 + ${novel} recettes élaborées ✨ seedés !`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
